### ISSUE TITLE
mfenced doesn't produce the right MathML

### ISSUE THREAD

**Issue by dpvc** [zorkow/speech-rule-engine#16]
The input

``` html
<math display="none">
  <mfenced open="(" close=")">
    <mi>a</mi><mi>b</mi>
  </mfenced>
</math>
```

produces the enriched output

``` html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="none">
  <mfenced open="(" close=")" type="fenced" role="leftright" id="6" children="5" content="3,4">
    <mo type="fence" role="open" id="3" parent="6" added="true" operator="fenced">(</mo>
    <mrow type="punctuated" role="sequence" id="5" children="0,2,1" content="2" parent="6">
      <mi type="identifier" role="latinletter" id="0" parent="5">a</mi>
      <mrow type="punctuation" role="comma" id="2" parent="5" operator="punctuated" />
      <mi type="identifier" role="latinletter" id="1" parent="5">b</mi>
    </mrow>
    <mo type="fence" role="close" id="4" parent="6" added="true" operator="fenced">)</mo>
  </mfenced>
</math>
```

This incorrectly inserts the open and close delimiters into the mfenced element (so they are doubled in the output), and groups all the children in a single mrow (preventing them fro getting their correct punctuation from the mfenced).

If you wanted to convert the mfenced to an mrow, that would resolve the issue with double delimiters.  But the default separator is a comma, not an empty mrow, as in the example above.

**Comment by zorkow** [comment]
Indeed mfenced does not work yet.
Next on the list.

**Comment by zorkow** [comment]
I've started addressing the mfenced issue. In some cases (e.g., around tables) it is quite straightforward. 
Other mfenced expressions (cf. tests 258 to 274) are not as simple. 
In the standard (or sane) case we would get some parentheses and a punctuated element, i.e. a comma separated list. That is easy to collapse and, while the punctuated element introduces a new mrow, we could disperse this as well as we otherwise might end up with rendering problems.
Unfortunately, both fences and separators can be anything, which makes things a lot more complex.

Test 263 exposes the problem nicely: We have two operations and a punctuation symbol as separators. Consequently we get a much more complex structure than just a separated value list. 
Trying to regain the simple mfenced structure will drop a lot of semantic.

**Comment by zorkow** [comment]
Btw. in 264 something odd happens with the maction.

**Comment by dpvc** [comment]
> Trying to regain the simple mfenced structure will drop a lot of semantic.

I don't think it is necessary to turn it back into an mfenced.  Since mfenced is supposed to be equivalent to the corresponding mrow with explicit mo elements, I think it is OK to produce the latter in place of the mfenced.  That should make things easier for you and more consistent for people using the enriched form (mfenced has been problematic for similar reasons in the past).

> in 264 something odd happens with the maction.

The collapsing code assumed that the delimiters were the first and last elements in the fenced element, which isn't the case when it is an actual mfenced element.

**Comment by zorkow** [comment]
> I don't think it is necessary to turn it back into an mfenced. 

Very good, that will indeed make life a lot easier and code cleaner.

**Comment by zorkow** [comment]
Mfenced are now fully rewritten into mrows with fences and separators.
