### ISSUE TITLE
Incomplete semantic tree structure in SVG renderer

### ISSUE THREAD

**Issue by zorkow** [zorkow/speech-rule-engine#21]
In accessibility tool:
SVG renderer omits some elements, leaving the tree structure in the data attributes incomplete.
Example of binomial coefficient.

**Comment by zorkow** [comment]
Add a data attribute with the overall tree structure using Collapsed_ type and store in top element.
This way we can continue walking even if bits are cut out by a renderer.

**Comment by dpvc** [comment]
There is a configuration parameter `addMMLclasses` that controls whether SVG tries to reduce the SVG structure or not.  So you might try setting that and see if it helps.

**Comment by zorkow** [comment]
addMMLclasses does not help in the case of tables. The mtr elements are always omitted.
Is there any way we can switch those on?

**Comment by dpvc** [comment]
You are right, neither HTML-CSS nor SVG output includes elements that correspond to the `mtr` nodes.  One reason for this is that the tables are layer out by columns rather than rows, so the structure doesn't match the MathML and there is no reasonable way to make an `mtr` in that case.  (The CommonHTML output is laid out in rows, and so does have elements that correspond to `mtr`, however).

The SVG output probably could be made to lay out in rows, but it would be a significant amount of work.  The HTML-CSS would require a major rewrite of how tables are handled in order to do that, and I doubt that it is worth it since we are moving toward replacing HTML-CSS by CommonHTML.

**Comment by dpvc** [comment]
PS, note that even in CommonHTML output, you will be limited in the type of highlighting you can do because the rows use `display:table-row` and those can have background color, but can't have borders, for example.

**Comment by zorkow** [comment]
Since this affects not only highlighting but walking in general, it's probably a good idea to remember the overall tree structure in the usual LISP style, just in case a layer has been "swallowed". This way we don't have to be careful when optimising for visual rendering.

**Comment by dpvc** [comment]
I'm not sure what you mean by "remember" here.

**Comment by zorkow** [comment]
Similar to our collapsed attribute, where we save the semantic tree structure, when nodes are omitted, we could just save the entire tree structure at the root. This way we can always continue walking even if a node has been cut.

**Comment by dpvc** [comment]
So do you mean include the `data-mathml` attribute?  Currently that is done by the AssistiveMML extension, so if you include that, you will get the `data-mathml` attribute with the copy of the original MathML.

**Comment by zorkow** [comment]
No, I was more thinking about putting the structure of the semantic tree into an object of the form:
(0 (1 2) (3 (4 5)))  etc. So if node 3 is missing, e.g., because it is a row, we can still continue walking on 4 and 5.
That'll make things a lot more lightweight and will decouple the walking from the MathML and also potentially the on the fly speech generation.

**Comment by dpvc** [comment]
OK, got it.  So this is something the enrichment extension would add, so I'll leave that to you.

**Comment by zorkow** [comment]
Fixed in v2.0.0-beta.
