### ISSUE TITLE
Standalone tool sre does not respond to locale es

### ISSUE THREAD

**Issue by dataopt** [zorkow/speech-rule-engine#234]
I have a file named `b.xml` with the following content:

```
<math xmlns='http://www.w3.org/1998/Math/MathML' display='block'>
<mrow>
  <mrow>
    <msup>
      <mi>x</mi>
      <mn>2</mn>
    </msup>
    <mo>+</mo>
    <mrow>
      <mn>4</mn>
      <mo>&InvisibleTimes;</mo>
      <mi>x</mi>
    </mrow>
    <mo>+</mo>
    <mn>4</mn>
  </mrow>
  <mo>=</mo>
  <mn>0</mn>
</mrow>
</math>
```

Using the standalone tool `sre` via the command
```
./sre --locale es -i b.xml 
```
gave the following output in English instead of Spanish:
```
sum with 3 summands x squared plus four times x plus four equals zero
```

**Comment by zorkow** [comment]
Thanks for reporting this. Sorry for the delay in getting  back to this project.

The reason is that `es` locale is currently only available for the mathspeak rule set. The default for the standalone engine is currently still the old chromevox rule set.
If you select the mathspeak rules explicitly:

```./sre --d mathspeak --locale es -i b.xml ```

you should get the output:

```x al cuadrado más 4 por x más 4 igual 0```
