### ISSUE TITLE
[a11y walker] highlighting wrong fence 

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#29]
From https://github.com/zorkow/speech-rule-engine/issues/24

On WebKit, in the CS equation, if I navigate to one of the closing paranthesis, it gets the background highlighting but its opening counterpart gets the foreground highlighting.

**Comment by pkra** [comment]
This bug is not specific to WebKit, correct?

**Comment by pkra** [comment]
I also see this on Chrome 45 but not on Chrome 47.

**Comment by dpvc** [comment]
It looks like this is [this bug](https://code.google.com/p/chromium/issues/detail?id=512081), fixed in blink but not WebKit itself.  It looks like it is specific to `<use>` elements, so it may be possible to work around it by enclosing the `<use>` in a `<g>`, at least temporarily while taking the measurement.

**Comment by dpvc** [comment]
The `issue29` branch of my fork of SRE includes a proposed work-around for this issue.
