### ISSUE TITLE
Title: SRE now returns raw keycodes on navigation hitting end-points:

### ISSUE THREAD

**Issue by tvraman** [zorkow/speech-rule-engine#352]
Description:
I updated to SRE 3.0.0-beta1-10 and noticed the following:
Where earlier, attempting to navigate  past the first/last/top node
returned (left), (right), etc as the error code, it's now returning
raw keycodes e.g. (38).

Interestingly, downgrading back to 2.4.0 does not appear to fix the
problem.

Did the update  mostly because github started warning about insecure
packages being pulled in by package-lock.json, those did go away after
the update.

**Comment by zorkow** [comment]
It could be a to change in behaviour of 'closure', but I don't really think it has anything to do with any third party packages.  
It could be due to some changes on the walkers I've made for the MathJax v3 integration.

Can you see if you reproduce the old behaviour when downgrading further, e.g., to 2.3?

**Comment by tvraman** [comment]
Following up to myself, I fixed this on the Emacspeak end to handle
38..40 in my error handler
