### ISSUE TITLE
Title: missingbreak?

### ISSUE THREAD

**Issue by tvraman** [zorkow/speech-rule-engine#360]
Description: file:
https://github.com/zorkow/speech-rule-engine/blob/master/src/audio/acss_renderer.js#L123
There is a missing break on this clause which makes the code look
assymmetric -- though it likely doesn't matter since it's returning a
value there.

Still having a hard time digging through sre to find where to make the
relevant ACss changes, there are so many evels of indirection that I'm
too scared to touch any of it:-)

**Comment by zorkow** [comment]
I see, easy fix.
The files you might want to change first are the speech rules for emacspeak here:
https://github.com/zorkow/speech-rule-engine/blob/master/src/speech_rules/emacspeak_rules.js

Btw., it's always best to branch off `develop` rather than master. That contains the latest fixes.

**Comment by tvraman** [comment]
looked at emacspeak_speech_rules.js already --- but it didn't shed much
light on how to change the acss values we apply for various things,
that's when I wrote the too many indirections lament/whine.
--

**Comment by zorkow** [comment]
That's pretty much how I felt when I first looked at ChromeVox code: To many layers of indirection.
And David always made me add some more....

Here is a brief overview:
* Emacspeak rules were originally a copy of the semantic ChromeVox rules (in `semantic_tree_rules.js`) and then adapted. They use the same personality annotations, we used to have for the Chrome TTS, i.e., pitch, rate and volume.
* Instead of navigation descriptions we now have auditory descriptions, which are generated by the speech rules, i.e, at text string plus context plus personality annotation.
* The audio renderers translate those auditory descriptions into whatever output we need, e.g., text, SSML, Sable, etc.
* Most functionality for the ACSS renderer is defined in the two abstract classes: `AbstractAudioRenderer` and `MarkupRenderer`.
* Markup renderers have a scale function to map personality annotations from the internal units into units they use. I think for Emacspeak we scale from [-2, 2] floats into [0, 10] integer interval.  

That's the pipeline in a nutshell. I hope that helps.
