### ISSUE TITLE
text to symbols conversion

### ISSUE THREAD

**Issue by lavanyaifet4** [zorkow/speech-rule-engine#384]
input = '<math` alttext="equation sequence t equals parameter estimate divided by standard error of estimate equals beta hat sub i divided by cap s times cap e sub beta hat sub i" display="block" xmlns="http://www.w3.org/1998/Math/MathML"><mstyle displaystyle="true"><mrow><mrow><mi>t</mi><mo>=</mo><mfrac><mrow><mtext>parameter</mtext><mtext>&#x2009;</mtext><mtext>estimate</mtext></mrow><mrow><mtext>standard</mtext><mtext>&#x2009;</mtext><mtext>error</mtext><mtext>&#x2009;</mtext><mtext>of</mtext><mtext>&#x2009;</mtext><mtext>estimate</mtext></mrow></mfrac><mo>=</mo><mfrac><mrow><msub><mover accent="true"><mi>&#x03B2;</mi><mo>&#x005E;</mo></mover><mi>i</mi></msub></mrow><mrow><mi>S</mi><msub><mi>E</mi><mrow><msub><mover accent="true"><mi>&#x03B2;</mi><mo>&#x005E;</mo></mover><mi>i</mi></msub></mrow></msub></mrow></mfrac></mrow></mrow></mstyle></math>`

domian:"clearspeak", style:"default"

Expected Output: "equation sequence part 1 t =  part 2 parameter estimate divided by standard error of estimate =  part 3 β ^ sub i divided by S ^ E sub β hat sub i"

Actual Output: "equation sequence part 1 t equals part 2 parameter estimate divided by standard error of estimate equals part 3 beta hat sub i divided by cap s times cap e sub beta hat sub i"

Symbols like equal =>=, beta=> β, cap => ^ are missing
speech-rule-engine version 2.1.1

**Comment by zorkow** [comment]
I am a bit confused on the output you expect: So you **do not** want symbol like `=` or `^` to be translated? I am afraid that is not really an option.

In case you are seeing output like your __Expected Output__, but actual want you __Actual Output__, then there is a problem with SRE not being able to find and load the maths mappings it needs to translate Unicode symbols. They are found in the sub-directories of the [`lib` directory](https://cdn.jsdelivr.net/npm/speech-rule-engine@2.1.1/lib/).

Finally, SRE only contains Clearspeak implementation since v2.3.0. So I suggest to upgrade your installation to the latest version (v3.0.1 stable or v3.1.0-beta.2 for dev) first.
