### ISSUE TITLE
Build failure with 3.1.1 on macOS

### ISSUE THREAD

**Issue by klobetime** [zorkow/speech-rule-engine#434]
Trying to build 3.1.1 on macOS Catalina (10.15.7), I ran into an error:
> [:~/src/speech-rule-engine-3.1.1] $ make
> sed: 1: "/Users/klobetime/src/sp ...": invalid command code k
> make: *** [/Users/klobetime/src/speech-rule-engine-3.1.1/node_modules/google-closure-library/sre_cleaned] Error 1

Turns out on mac the sed command expects an argument for the -i flag causing a line in the Makefile update introduced in #374 to fail. I changed it to read `@sed -i '' -e s/"^.*@deprecated Use ES6.*"// $(GOOG_BASE)` and everything went smoothly.

I didn't create a pull request because I'm assuming this will break a bunch of other platforms, but thought I'd share.

**Comment by zorkow** [comment]
Thanks for reporting this.  
I've copied a suggestion [from stackoverflow](https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux), which provides a solution that works under both Mac and Linux.

The real issue is, that closure throws an error on it's own library. While moving to a newer version might solve this, it would also require to rewrite classes into ES6 notation. Instead of doing this, I am hoping to eventually move the codebase to Typescript altogether.

**Comment by klobetime** [comment]
Because you are now creating a backup file with the sed command, seems like you could set `GOOG_BASE_CLEAN` to be something like `$(GOOG_BASE).bak` and skip the touch and creation of the marker file entirely. But glad this'll be fixed regardless. :)
Thanks!
