### ISSUE TITLE
Different speech results from different api calls

### ISSUE THREAD

**Issue by kevinMarshallTexthelp** [zorkow/speech-rule-engine#51]
If pass 
`<math xmlns="//www.w3.org/1998/Math/MathML">
    <mrow>
      <msup>
        <mi>x</mi>
        <mn>2</mn>
      </msup>
      <mo>+</mo>
      <msup>
        <mi>x</mi>
        <mn>3</mn>
      </msup>
      <mo>+</mo>
      <msup>
        <mi>x</mi>
        <mn>4</mn>
      </msup>
      <mo>+</mo>
      <msup>
        <mi>x</mi>
        <mn>5</mn>
      </msup>
    </mrow>
  </math>`
to 
 `sre.System.getInstance().toSpeech` 

it will return

> x squared plus x cubed plus x Superscript 4 Baseline plus x Superscript 5

but if you pass the same to 

`sre.Enrich.semanticMathmlSync` 

the speech returned will be

> x squared plus x cubed plus x Superscript 4 plus x Superscript 5

**Comment by zorkow** [comment]
I can see that, too.
The semantic enrichment can rewrite the MathML (e.g., group elements together or introduce invisible operators). However they should produce the same output for the mathspeak rule set, in particular, since they should the same semantic tree. 
Currently, I can only guess that something goes wrong with the caching or the way speech generation is called internally.

**Comment by zorkow** [comment]
Fixed in PR #59 .
