### ISSUE TITLE
Operator instead of Fence

### ISSUE THREAD

**Issue by zorkow** [zorkow/speech-rule-engine#7]
On expression

(\mid x\mid )

gives MathML

``` html
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mo stretchy="false">&#x2223;<!-- ∣ --></mo>
  <mi>x</mi>
  <mo stretchy="false">&#x2223;<!-- ∣ --></mo>
</math>
```

which is classified as operator instead of fence.

**Comment by zorkow** [comment]
@dpvc

Unicode Hex	U+2223
Character Name	DIVIDES

Is that intended?

**Comment by zorkow** [comment]
While I could still understand \mid, for 
\(\lvert  x\rvert \)
I get the same result.

**Comment by zorkow** [comment]
MathJax could map 
\lvert, \rvert etc. to  U+007C
and \mid, \divides, \mvert, \vert, etc onto U+2223

**Comment by dpvc** [comment]
Sigh.  These go back to the early days of MathJax, when I didn't know as much about unicode as I do now, and fonts with appropriate characters were hard to come by.  One of the considerations at the time was that the glyph for U+007C in the STIX font does not extend below the baseline, so `|x|` doesn't look right to many people in that font.  On the other hand, U+2223 does descend below the baseline, so works better visually.

You are right that `\lvert` and `\rvert` probably should be U+007C, and similarly `\lVert` and `\rVert` should be U+2016 rather than U+2225.  Unfortunately, the MathJax fonts don't have coverage for U+2016 (though we could remap internally to U+2225).  This is one of the things that needs to be fixed when we do the font-fix update.  We would also need to do some more careful remapping of STIX U+007C to get an appropriate glyph.  I'll open an issue for it on MathJax proper.

**Comment by pkra** [comment]
@dpvc could you check if STIX 2 has changed the issue with descending below the baseline? I'm not sure we mentioned this in our feedback way back when.

**Comment by dpvc** [comment]
It does look like STIX 2 has adjusted the vertical bar at U+007C.  I don't know if they are going to continue to distribute these in the older format (STIXGeneral, etc) that MathJax can use.  The current STIXMath font uses font features, so we are not able to use this font currently, if it is installed locally (just as we can't use the STIX 1.1 version of STIXmath).  I'm not sure what they intend for their "Web font" distribution.  I haven't tried Fred's code for breaking it up yet.

**Comment by pkra** [comment]
> It does look like STIX 2 has adjusted the vertical bar at U+007C.

Great.

> I don't know if they are going to continue to distribute these in the older format (STIXGeneral, etc) that MathJax can use

I don't think they want to.

> The current STIXMath font uses font features, so we are not able to use this font currently, if it is installed locally (just as we can't use the STIX 1.1 version of STIXmath). 

Could you report that? (Or do you want me to?) STIX considers MathJax an important target and so they will likely take this seriously.

> I'm not sure what they intend for their "Web font" distribution. I haven't tried Fred's code for breaking it up yet.

We are their web font distribution so we need to help / provide input.

**Comment by pkra** [comment]
not "distribution" but "provider"

**Comment by zorkow** [comment]
Semantic has worked for a long time. The speech is now adapted as well.
